feat(bpdm-gate): Extend error code
eclipse-tractusx/bpdm pull request #1003
Opened 2024-07-18 13:53 UTC by kunyao-cofinity-x

## Description

Enhance the error handling mechanism for the orchestrator and gate components by extending the list of available error codes. This will improve the visibility and detail of error information, particularly beneficial for the customer dashboard to understand why a data set could not be processed.

Currently, the orchestrator and gate components have a limited set of error codes. Extending these error codes will provide more granular information on processing failures, aiding in quicker diagnosis and resolution. This feature will update both the orchestrator and gate components to support a more comprehensive list of error codes.

Benefits

- Improved Transparency: Customers can view detailed error reasons on the dashboard, enhancing trust and user experience.

- Enhanced Debugging: Developers and support teams can identify and resolve issues more efficiently with detailed error information.

- Better Monitoring: Allows for more precise monitoring and logging of errors, leading to improved system reliability.

New error types add to the following two classes

- org.eclipse.tractusx.bpdm.gate.api.exception.BusinessPartnerSharingError
- org.eclipse.tractusx.orchestrator.api.model.TaskErrorType

New error types

- NaturalPersonError - The provided record contains natural person information.
- BpnErrorNotFound - The provided record can not be matched to a legal entity or an address.
- BpnErrorTooManyOptions - The provided record can not link to a clear legal entity.
- MandatoryFieldValidationFailed - The provided record does not fulfill mandatory validation rules.
- BlacklistCountryPresent - The provided record is part of a country that is not allowed to be processed by the GR process (for example: Brazil).
- UnknownSpecialCharacters - The provided record contains unallowed special characters.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-07-29 04:36 UTC, nicoprow requested changes
Sadly, the Schema annotation does not work with the used OpenAPI library after all. I discovered this, while improving the Orchestrator documentation. Please have a look at this file: https://github.com/eclipse-tractusx/bpdm/blob/fbeeb51154743e6e6700c9c7f9f4815399bce415/bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartner.kt#L73

I had to write the OpenAPI description on the field description of the referencing class.

This would be in your case here:
https://github.com/eclipse-tractusx/bpdm/blob/fbeeb51154743e6e6700c9c7f9f4815399bce415/bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskErrorDto.kt#L27

And here:
https://github.com/eclipse-tractusx/bpdm/blob/fbeeb51154743e6e6700c9c7f9f4815399bce415/bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/SharingStateDto.kt#L40


Also, the code mapping TaskErrorType to GateErrorType is currently missing.

2024-12-04 06:23 UTC, nicoprow requested changes
@kunyao-cofinity-x 

Your contribution code is fine but some formalities are missing.

1. Please rebase to the newest state of main
2. Sine your contribution changes the API of Gate and Orchestrator please add the updated openAPI documents in the docs/api folder
3. Add a CHANGELOG entry with a reference to the issue

After that, the contribution is ready to merge

2024-12-06 07:12 UTC, SujitMBRDI approved these changes
LGTM

2024-12-06 07:16 UTC, merged

2024-12-06 08:49 UTC, nicoprow commented
Contributes to https://github.com/eclipse-tractusx/sig-release/issues/727