bugfix(bpdm-gate): fetched and attached legal name of entity while performing partner upload process.
eclipse-tractusx/bpdm pull request #1142
Opened 2024-12-02 09:29 UTC by SujitMBRDI

## Description

In this pull request, we have added functionality for getting Legal Name from Pool service while performing partner upload process via CSV file. As per the standards, we should have legal name attached and now we are fetching legal name for particular legal entity based on tenantBpnl(User BPNL).

Fixes #1141 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-12-02 10:36 UTC, kunyao-cofinity-x reviewed
Looks fine to me

2024-12-02 11:07 UTC, SujitMBRDI commented
> Looks fine to me

Hi @kunyao-cofinity-x, thanks for reviewing!! If it all ok then could you please approve the pull request.
Otherwise, it will keep on showing me that i have some review comments to work on.
![image](https://github.com/user-attachments/assets/1aac4f60-4629-4402-adc7-fe9dce0b3623)

2024-12-02 11:12 UTC, kunyao-cofinity-x approved these changes

2024-12-02 12:50 UTC, kunyao-cofinity-x approved these changes

2024-12-03 03:53 UTC, nicoprow approved these changes
LGTM

2024-12-03 03:53 UTC, nicoprow requested changes
Wait I take it back :D

code looks good to me but please adhere to the commit convention and rename `bugfix` to `fix`

2024-12-03 05:01 UTC, dilipdhankecha2530 commented
LGTM

2024-12-03 05:02 UTC, dilipdhankecha2530 approved these changes

2024-12-03 05:44 UTC, SujitMBRDI commented
> Wait I take it back :D
> 
> code looks good to me but please adhere to the commit convention and rename `bugfix` to `fix`

Hi @nicoprow, i have amended commit and also edited the tittle.

2024-12-03 06:34 UTC, nicoprow approved these changes
LGTM

2024-12-03 06:38 UTC, merged