feat: Update linkage between bpns and add support to update the data in gate from pool
eclipse-tractusx/bpdm pull request #1160
Opened 2024-12-12 10:25 UTC by dilipdhankecha2530

## Description

This PR contains the development to update the linkage from LegalAddress to LegalAndSiteMainAddress and AdditionalAddress to SiteMainAddress. Also add the method in Gate to handle the update of BPNS based on the changeLog entries.

Issue: https://github.com/eclipse-tractusx/bpdm/issues/1121

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-12-17 05:20 UTC, SujitMBRDI requested changes
Over all changes looks good to me.
Please update CHANGELOG.

2024-12-17 05:20 UTC, SujitMBRDI commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordUpdateServices.kt
> +            businessPartner.siteConfidence = ConfidenceCriteriaDb(false,false,0, LocalDateTime.now(), LocalDateTime.now(),0)
In future, we need to change LocalDateTime to Instant on entity level but not for now.

2024-12-20 06:13 UTC, nicoprow approved these changes
I tested it and works for me. Test I have done:

1. Create a business partner without site information and address type additional address
2. Share and wait for BPNs
3. Create a business partner with same BPNL and same BPNA with site information and address type SiteMainAddress.
4. After successful sharing I can see that in the output the BPNA stays the same but the address type successfully changed to sitemainaddress

2025-01-06 11:11 UTC, SujitMBRDI approved these changes

2025-01-07 06:24 UTC, merged