fix(gate): fixed the persistence of AddressIdentifier
eclipse-tractusx/bpdm pull request #326
Opened 2023-07-11 10:42 UTC by cezaralexandremorais

fixed the persistence of the identifiers collection on LogisticAddress

2023-07-13 11:13 UTC, nicoprow requested changes
I tried the feature and when updating/creating addresses directly it works. But when updating/creating legal entities or sites, the identifiers are not saved in the legal addresses and main addresses.

2023-07-18 08:00 UTC, nicoprow requested changes
Works as intended  but I just noticed in the Tests you ignore the identifiers fields when comparing. I think it's better to compare them as well and really cover the identifiers in the tests again.

2023-07-26 12:06 UTC, cezaralexandremorais commented
> Works as intended but I just noticed in the Tests you ignore the identifiers fields when comparing. I think it's better to compare them as well and really cover the identifiers in the tests again.

Done, made some changes to validate identifiers on tests

2023-07-26 13:26 UTC, nicoprow approved these changes

2023-07-26 13:27 UTC, merged