feat: API - Rename fields & enums LsaType/ChangelogSubject to BusinessPartnerType
eclipse-tractusx/bpdm pull request #361
Opened 2023-07-26 13:36 UTC by martinfkaeser

- Rename and combine enums **LsaType** & **ChangelogSubject** into common **BusinessPartnerType**
- Rename field names **lsaType** & **changelogSubject** to **businessPartnerType** including *DB field*

Fixes #351

2023-07-26 14:36 UTC, martinfkaeser commented
Please merge only after https://github.com/eclipse-tractusx/bpdm/pull/359 for DB migrations to be executed in intended sequence!

2023-07-31 14:52 UTC, nicoprow requested changes
Need to resolve conflicts and migration file version needs an update due to a previous merge of a pull request. 

Otherwise looks good to me

2023-08-01 07:15 UTC, martinfkaeser commented
> Need to resolve conflicts and migration file version needs an update due to a previous merge of a pull request.
> 
> Otherwise looks good to me

Done

2023-08-03 10:32 UTC, nicoprow approved these changes

2023-08-03 10:33 UTC, merged