Feat/output endpoints generic bpm
eclipse-tractusx/bpdm pull request #437
Opened 2023-09-05 09:22 UTC by rainer-exxcellent

## Description
Created endpoints for uploading and searching generic business partner output data.

### Solves

#387

2023-09-06 07:27 UTC, martinfkaeser commented on bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateBusinessPartnerApi.kt
> +    fun getLegalEntitiesOutput(
Consistent naming: Rename to `getBusinessPartnersOutputByExternalIds`?

2023-09-06 07:38 UTC, martinfkaeser commented
I would suggest renaming the interface / data classes:
- IBaseBusinessPartnerInputDto -> IBaseBusinessPartnerDto (used as basis for both input and output)
- BusinessPartnerInputDto -> BusinessPartnerInputResponse
- BusinessPartnerOutputDto -> BusinessPartnerOutputResponse

2023-09-07 07:10 UTC, rainer-exxcellent commented
> I would suggest renaming the interface / data classes:
> 
>     * IBaseBusinessPartnerInputDto -> IBaseBusinessPartnerDto (used as basis for both input and output)
> 
>     * BusinessPartnerInputDto -> BusinessPartnerInputResponse
> 
>     * BusinessPartnerOutputDto -> BusinessPartnerOutputResponse

Most of the class in the response package end with Dto. So it is named consistently.
We should first discuss about the naming before we change this.

2023-09-07 08:13 UTC, martinfkaeser commented
> > I would suggest renaming the interface / data classes:
> > ```
> > * IBaseBusinessPartnerInputDto -> IBaseBusinessPartnerDto (used as basis for both input and output)
> > 
> > * BusinessPartnerInputDto -> BusinessPartnerInputResponse
> > 
> > * BusinessPartnerOutputDto -> BusinessPartnerOutputResponse
> > ```
> 
> Most of the class in the response package end with Dto. So it is named consistently. We should first discuss about the naming before we change this.

I would suggest naming the DTOs that are only used in a request `...Request` (and put them in the request package), the DTOs that are only used in a response `...Response` (and put them in the response package) and the ones which are used in both contexts `...Dto`.
All the DTOs in the gate/request package are consistently named `...Request`.
I don't know why there is a mix of `...Dto` and `...Response` in the gate/response package, but feels inconsistent.

2023-09-08 12:24 UTC, nicoprow requested changes
Code looks good to me.

Please squash the commits in the history. They only contain rebase fixes and adjustments from review.

2023-09-11 08:14 UTC, nicoprow approved these changes

2023-09-11 08:14 UTC, merged