feat(Gate): Added new generic data model with migration files and uni…
eclipse-tractusx/bpdm pull request #438
Opened 2023-09-05 15:30 UTC by fabiodmota

## Description
This PR introduces generic data model entities alongside the migration files. 
The tests focus on the CRUD operations for entities like `BusinessPartner`, `Roles`, `Identifier`, `State`, `Classification`, `PostalAddress`, `PhysicalPostalAddress`, and `AlternativePostalAddress`.

The goal is to ensure that the basic functionalities for these entities are working as expected, and any future changes won't inadvertently break existing functionalities.

issue https://github.com/eclipse-tractusx/bpdm/issues/382

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-09-06 10:35 UTC, martinfkaeser requested changes

2023-09-06 10:35 UTC, martinfkaeser commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartner.kt
> +    val genericClassification: MutableSet<GenericClassification> = mutableSetOf()
rename to `classifications`

2023-09-06 10:35 UTC, martinfkaeser commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartner.kt
> +
Field `roles` missing

2023-09-06 10:35 UTC, martinfkaeser commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartner.kt
> +    var address: Address? = null
rename to `postalAddress`

2023-09-06 10:35 UTC, martinfkaeser commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartner.kt
> +    var isOwner: Boolean?,
non-optional

2023-09-06 10:35 UTC, martinfkaeser commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartner.kt
> +    var addressBpn: String?,
rename to bpnA, bpnL, bpnS

2023-09-06 10:35 UTC, martinfkaeser commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/GenericClassification.kt
> +    var type: String?,
I think it should be 
`@Enumerated(EnumType.STRING)
    val type: ClassificationType,` 
like in LegalEntityClassification

2023-09-06 10:35 UTC, martinfkaeser commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/State.kt
> +    var type: String?,
Should be
`@Enumerated(EnumType.STRING)
    val type: BusinessStateType,`

2023-09-06 10:35 UTC, martinfkaeser commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/State.kt
> +    var validFrom: Instant?,
Type should be `LocalDateTime?` like in LegalEntityState

2023-09-06 10:35 UTC, martinfkaeser commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/GenericRole.kt
> +class GenericRole(
Can be replaced (hopefully) by
`@Enumerated(EnumType.STRING)
@ElementCollection
    val roles: MutableSet<BusinessPartnerRole> = mutableSetOf()`
in BusinessPartner entity

2023-09-06 13:35 UTC, martinfkaeser commented on bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/GenericEntitysTestIT.kt
> +internal class GenericEntitysTestIT @Autowired constructor(
Rename to maybe `BusinessPartnerIT` ?

2023-09-06 16:48 UTC, fabiodmota commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartner.kt
> +    var externalId: String?,
fixed

2023-09-06 16:48 UTC, fabiodmota commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartner.kt
> +    var nameParts: String?,
fixed

2023-09-06 16:48 UTC, fabiodmota commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartner.kt
> +    val genericClassification: MutableSet<GenericClassification> = mutableSetOf()
fixed

2023-09-06 16:48 UTC, fabiodmota commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartner.kt
> +
fixed

2023-09-07 09:55 UTC, martinfkaeser commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/State.kt
> +    var type: String?,
should be non-optional: BusinessStateType

2023-09-08 06:21 UTC, martinfkaeser commented
I think we need, same as in `LegalEntity` etc., something like
`var dataType: OutputInputEnum`

I don't like the naming dataType though. Can we maybe call it
`var stage: StageType`?
Let's discuss!

2023-09-08 06:27 UTC, martinfkaeser commented
Although it's not explicitly required, should we make all our BusinessPartner relations preserve their order, just like `nameParts`?
`identifiers`, `states`, `classifications`, maybe even `roles`?
I think in general a predictable order is the preferred option and it's easy to implement, just adding the `@OrderColumn` annotation.
Let's discuss it!

2023-09-08 12:51 UTC, nicoprow reviewed
Looks good to me, just needs a rebase to remove the current conflicts

2023-09-11 12:55 UTC, nicoprow approved these changes

2023-09-11 12:56 UTC, merged