feat(bpdm-testing): create verbose business partner objects
eclipse-tractusx/bpdm pull request #448
Opened 2023-09-11 12:53 UTC by SujitMBRDI

## Description

In this pull request, created Business Partner Objects of Verbose DTO type and updated them with response values-object. which can be utilised while running test classes.

2023-09-22 06:45 UTC, rainer-exxcellent reviewed
I think it would be better to derive the response values from the request values,
like in the suggestions i made

2023-09-22 06:45 UTC, rainer-exxcellent commented on bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/util/ResponseValues.kt
> +        technicalKey = "LF1",
```suggestion
        technicalKey = RequestValues.legalForm1.technicalKey,
```

2023-09-22 06:45 UTC, rainer-exxcellent commented on bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/util/ResponseValues.kt
> +        name = "Limited Liability Company",
```suggestion
        name = RequestValues.legalForm1.name,
```

2023-09-22 06:45 UTC, rainer-exxcellent commented on bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/util/ResponseValues.kt
> +        abbreviation = "LLC",
```suggestion
        abbreviation =  RequestValues.legalForm1.abbreviation,
```

2023-09-22 07:27 UTC, SujitMBRDI commented
> I think it would be better to derive the response values from the request values, like in the suggestions i made

@rainer-exxcellent thanks for feedback, 
I agree and will update pr accordingly, @nicoprow, also suggested same but with otherway i.e. all request values should be derived from response values and it will be beneficial too.

2023-09-22 13:18 UTC, SujitMBRDI commented
> > I think it would be better to derive the response values from the request values, like in the suggestions i made
> 
> @rainer-exxcellent thanks for feedback, I agree and will update pr accordingly, @nicoprow, also suggested same but with otherway i.e. all request values should be derived from response values and it will be beneficial too.

@nicoprow, @rainer-exxcellent @martinfkaeser, I have updated changes we discussed and resolved conflict too.
Kindly again review the pull request.

2023-09-25 07:57 UTC, nicoprow requested changes
Commits can be squashed, especially since the first commit is basically reverted through the subsequent commits. I don't see that the provided commits in the history make sense here. Either squash to one commit or divide the commits into something like name change, common value replacement in verbose values and common value replacement in non-verbose values.

I like nonVerboseValues better than requestValues as the name more accurately depicts how the values are actually used. But I'm still not on board with the name nonVerbose. Would like to have a more concise name differentating between verbose and non-verbose DTOs in the Pool. I suggest we have a discussion about it and come to a conclusion

2023-09-25 09:20 UTC, SujitMBRDI commented
> Commits can be squashed, especially since the first commit is basically reverted through the subsequent commits. I don't see that the provided commits in the history make sense here. Either squash to one commit or divide the commits into something like name change, common value replacement in verbose values and common value replacement in non-verbose values.
> 
> I like nonVerboseValues better than requestValues as the name more accurately depicts how the values are actually used. But I'm still not on board with the name nonVerbose. Would like to have a more concise name differentating between verbose and non-verbose DTOs in the Pool. I suggest we have a discussion about it and come to a conclusion

@nicoprow As we discussed, i kept  nonVerboseValues name for object class as it is and squashed commits to the one.
Kindly review pull request again

2023-09-25 10:41 UTC, nicoprow approved these changes

2023-09-25 10:42 UTC, merged