feat(Orchestrator): Add new workflow for Orchestrator service module …
eclipse-tractusx/bpdm pull request #478
Opened 2023-09-20 12:42 UTC by fabiodmota

## Description

We added a new helm chart to the existing structure to be able to deploy the new Orchestrator service module.

issue: https://github.com/eclipse-tractusx/bpdm/issues/461

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-09-21 07:58 UTC, nicoprow commented
Pull request is currently blocked due to having no orchestrator application released on Dockerhub

2023-10-02 11:29 UTC, fabiodmota commented
The Lint Test for the charts continues to fail due to issues with probes or resources. After conducting various tests and trying different increments of time for timeouts and readiness probes, I continue to encounter problems with the probes. Each app is deployed individually without issue, but when deploying the global bpdm for all apps, the problem always relates to resources or failed probes due to not being ready and is not always the same pod.

Below are some tests I conducted, and I have already communicated the issue to the respective DevSecOps Team:

Tests:
1. Deployed only bpdm parent -> failed
2. Deployed only subcharts -> failed
3. Deployed bpdm parent with pool -> success
4. Deployed bpdm parent with pool and orchestrator enabled -> success
5. Deployed bpdm parent with pool, gate, and orchestrator enabled -> failed
6. Deployed bpdm parent with pool, orchestrator, and cleaning service -> success
7. Deployed bpdm parent with pool, orchestrator, cleaning, and bridge service -> success
8. Deployed bpdm parent with pool, orchestrator, cleaning, bridge, and gate service -> failed
9. Deployed bpdm parent with pool and gate -> success
10. Deployed bpdm parent with pool, gate, orchestrator, cleaning, and bridge service (with different resources requested, more for pool and gate, less for others) -> failed
11. Deployed bpdm parent with pool, gate, and orchestrator enabled (with more resources requested for pool and gate) -> failed
12. Deployed bpdm parent with pool, gate, and orchestrator enabled (with more delay on initial startup probe for gate and pool) -> failed
13. Deployed bpdm parent with pool, gate, and orchestrator enabled (with more delay on initial startup probe for all apps) -> failed
14. Deployed bpdm parent with pool, gate, and orchestrator enabled (with more delay on initial startup probe for all apps and less resources for all) -> failed
15. Deployed bpdm parent with pool, gate, and orchestrator enabled (with more delay on initial startup probe for pool, gate, and open search and downgrade resources for all (pool, gate, and open search have more than others)) -> failed

DevSecTeam: @Siegfriedk @almadigabor

2023-10-16 14:31 UTC, fabiodmota commented
Any update on the runners ? @gabyertl

2023-10-17 07:39 UTC, almadigabor commented
> Any update on the runners ? @almadigabor 

We haven't received any updates unfortunately. For the time being either ignore the failed check (if it is indeed resource related) or disabled some helm dependencies/adjust resource requests.

2023-10-17 12:29 UTC, Siegfriedk commented
@fabiodmota we got feedback from EF that something was signed last week. Haven't seen a change yet. Unfortunate most EF peple are on the eclipse con this week

2023-10-18 10:57 UTC, nicoprow requested changes
Please rebase to current main and resolve the conflicts. After that, it's ready to merge

2023-10-19 06:51 UTC, almadigabor commented on charts/bpdm/Chart.yaml
If you make changes to the Chart.yaml or any other file within the your helm chart you also need to bump the `version` attribute otherwise the helm lint and test workflow will fail.

2023-10-19 14:27 UTC, nicoprow requested changes

2023-10-19 14:27 UTC, nicoprow commented on charts/bpdm/charts/bpdm-orchestrator/README.md
> +        - path: /bridge
example path should be orchestrator instead

2023-10-19 15:08 UTC, nicoprow approved these changes

2023-10-19 15:38 UTC, merged