Feat(Gate) - Allow user to input nullable values (Only External-ID is required)
eclipse-tractusx/bpdm pull request #523
Opened 2023-10-13 14:20 UTC by alexsilva-CGI

## Description

Some fields on the DTO's for upserting a Business Partner have been altered to only require an External-ID for creating an new 
Business Partner. All other fields are optional.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-10-16 14:29 UTC, fabiodmota approved these changes
LGTM , passed objects to null and filtered logic based on some fields that can be null

2023-10-18 11:09 UTC, nicoprow requested changes

2023-10-18 11:09 UTC, nicoprow commented on bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerBuildService.kt
> +    private fun toEntity(dto: ClassificationDto, partner: LegalEntity): LegalEntityClassification? {
The changes to the nullable DTO fields should not affect the Pool. Please split off a Pool specific DTO for the classification and keep the type there non-nullable. There should be a commin Classification base DTO interface which both Pool and the other modules' DTOs inherit from.

2023-10-18 11:09 UTC, nicoprow commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
> +        Identifier(type = dto.type.toString(), value = dto.value.toString(), issuingBody = dto.issuingBody)
Why is the toString method invocation needed here?

2023-10-25 07:47 UTC, nicoprow commented
Closing due to being duplicate #553

2023-10-25 07:47 UTC, closed without merging