feat(gate): Renamed the field "isOwner" to "isOwnCompanyData" in OpenAPI
eclipse-tractusx/bpdm pull request #545
Opened 2023-10-20 08:56 UTC by cezaralexandremorais

Renamed the field "isOwner" to "isOwnCompanyData" in OpenAPI

solves #510

2023-10-20 11:58 UTC, nicoprow requested changes

2023-10-20 11:58 UTC, nicoprow commented on bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/IBaseBusinessPartnerGateDto.kt
> +    @get:Schema(name = "isOwnCompanyData", description = "True if the sharing member declares itself as the owner of the business partner.")
better to just remove the whole name override. No need to have a name override there. Springdoc should just take the name of the field instead

2023-10-20 13:16 UTC, fabiodmota approved these changes

2023-10-23 06:57 UTC, nicoprow approved these changes

2023-10-23 06:58 UTC, merged