feat(pool): #556 Upsert Business Partners from Cleaning Result - refactoring
eclipse-tractusx/bpdm pull request #558
Opened 2023-10-25 04:55 UTC by rainer-exxcellent

## Description

Refactore code to reuse logic to convert dtos to entities. Add some abstrct methods to Interfaces to suport this.

## Pre-review checks

Solves issue #556 partly

2023-10-26 11:48 UTC, nicoprow approved these changes

2023-11-07 15:21 UTC, nicoprow requested changes
Since there have been other refactoring changes to the Pool I would suggest to be cautious and rebase to the current main first.

If there are no issues with test execution, the pull request would be ready to merge

2023-11-08 12:47 UTC, rainer-exxcellent commented
I rebased the branch to  the current main

2023-11-09 10:38 UTC, nicoprow approved these changes

2023-11-09 10:38 UTC, merged