feat(Pool): Fix controller naming
eclipse-tractusx/bpdm pull request #595
Opened 2023-11-02 12:59 UTC by fabiodmota

## Description
Endpoint controller for getting Legal Entityes is called searchSites

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-11-02 13:00 UTC, fabiodmota commented
I am leaving this commit as a subject for review, but isn't this controller named incorrectly?
I only opened a PR to be able to validate, I would appreciate if you could also take a look before we merge.

@nicoprow @rainer-exxcellent

2023-11-02 13:16 UTC, nicoprow approved these changes

2023-11-02 13:17 UTC, nicoprow requested changes
Actually, it's not a feature but a refactor

Please change the commit description accordingly

2023-11-10 11:31 UTC, nicoprow approved these changes

2023-11-10 11:57 UTC, merged