Refactor (bpdm) - Creation of Auth YML's and Path changes
eclipse-tractusx/bpdm pull request #655
Opened 2023-11-27 13:32 UTC by alexsilva-CGI

Solves remaining points raised on PR #623.

Solve #572

Should be merged only after #623 conclusion.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-11-29 06:22 UTC, nicoprow requested changes
Please rebase this branch onto the current main, then it will be easier to review

2023-12-07 03:06 UTC, nicoprow requested changes
I gave some feedback exemplary for the Dummy-Bridge configuration. But the same feedback counts for all the other applications as well.

2023-12-07 03:06 UTC, nicoprow commented on bpdm-bridge-dummy/src/main/resources/application-gate-auth.yml
> +          catena-keycloak-provider:
This hear specifies a new connection to a oauth2 server named "catena-keycloak-provider". The problem with this is that also the pool-client has the same client name. Better call them separately. Here "gate-oauth2-provider" and in the pool-auth "pool-oauth2-provider". That way both clients don't need to be under the same oauth2 host but may be secured through different servers. (Think about connecting a dev pool with an int gate for testing purposes for example)

2023-12-07 03:06 UTC, nicoprow commented on bpdm-bridge-dummy/src/main/resources/application-gate-auth.yml
> +            provider: catena-keycloak-provider
Replace the provider name with the new name according to the comment above

2023-12-07 03:06 UTC, nicoprow commented on bpdm-bridge-dummy/src/main/resources/application-gate-auth.yml
> +      oauth2-client-registration: bridge-client
replace bridge-client name with the new one. (See comment further down below)

2023-12-20 08:12 UTC, nicoprow requested changes
Looks good, just contains some incorrect path names with 'permission'. Since the properties are now again under security, those paths have to be adjusted

2023-12-20 08:12 UTC, nicoprow commented on bpdm-bridge-dummy/src/main/resources/application-gate-auth.yml
> +            client-id: ${bpdm.security.permission.client-id}
Should by now bpdm.security.client-id as it is not under permission anymore

2023-12-20 08:12 UTC, nicoprow commented on bpdm-bridge-dummy/src/main/resources/application-pool-auth.yml
> +            issuer-uri: ${bpdm.security.permission.auth-server-url:http://localhost:8180}/realms/${bpdm.security.permission.realm:master}
Also contains incorrectly 'permission'

2023-12-20 08:12 UTC, nicoprow commented on bpdm-bridge-dummy/src/main/resources/application-pool-auth.yml
> +            client-id: ${bpdm.security.permission.client-id}
Also here

2023-12-20 08:12 UTC, nicoprow commented on bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/config/SecurityConfig.kt
> +    value = ["bpdm.security.permission.enabled"],
Should be without permission

2023-12-20 08:12 UTC, nicoprow commented on bpdm-gate/src/main/resources/application-auth.yml
> +          jwk-set-uri: ${bpdm.security.permission.auth-server-url}/realms/${bpdm.security.permission.realm}/protocol/openid-connect/certs
permission in path here as well

2023-12-20 08:12 UTC, nicoprow commented on bpdm-gate/src/main/resources/application-orchestrator-auth.yml
> +            issuer-uri: ${bpdm.security.permission.auth-server-url:http://localhost:8180}/realms/${bpdm.security.permission.realm:master}
here

2023-12-20 08:12 UTC, nicoprow commented on bpdm-gate/src/main/resources/application-orchestrator-auth.yml
> +            client-id: ${bpdm.security.permission.client-id}
here

2023-12-20 08:12 UTC, nicoprow commented on bpdm-pool/src/main/resources/application-orchestrator-auth.yml
> +            issuer-uri: ${bpdm.security.permission.auth-server-url:http://localhost:8180}/realms/${bpdm.security.permission.realm:master}
here

2023-12-20 08:12 UTC, nicoprow commented on bpdm-pool/src/main/resources/application-orchestrator-auth.yml
> +            client-id: ${bpdm.security.permission.client-id}
and here

2024-01-10 11:17 UTC, alexsilva-CGI commented
Hello @nicoprow, I believe I did the required chances. Is there anything missing? Thanks

2024-01-11 04:44 UTC, nicoprow approved these changes
Everything looks good, I just wanted to wait for the merge after the latest alpha release

2024-01-11 04:46 UTC, merged