Fix (Pool) - Added way to LegalAddress to be Main Site Address in Pool
eclipse-tractusx/bpdm pull request #674
Opened 2023-12-06 14:10 UTC by alexsilva-CGI

## Description

Currently, it is not possible in the Pool for a legal address to be also a main site address at the same time. This PR adjust the way a Address is persisted if both Legal Entity and Site share it.

Related issues: #657 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-12-06 15:36 UTC, alexsilva-CGI commented
@nicoprow Tested with the round trip, and it seems that its now associating both site and legalEntity to an address when the LegalAndSiteMainAddress is present on the AddressType. 

I do have a question. Should also this logic apply when an update is done? so for example when type changes from SiteMainAddress to LegalAndSiteMainAddress, an association from both Site and Legal Entity to a single Address is done, with the deletion of the old persisted addresses. Thanks

2023-12-07 02:29 UTC, nicoprow commented
> @nicoprow Tested with the round trip, and it seems that its now associating both site and legalEntity to an address when the LegalAndSiteMainAddress is present on the AddressType.
> 
> I do have a question. Should also this logic apply when an update is done? so for example when type changes from SiteMainAddress to LegalAndSiteMainAddress, an association from both Site and Legal Entity to a single Address is done, with the deletion of the old persisted addresses. Thanks

For the update I would follow the same principle we have done before: The parent relationship between L/S/A business partners doesn't change

2023-12-07 03:56 UTC, nicoprow approved these changes

2023-12-07 03:56 UTC, nicoprow commented on bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt
> +            if (taskEntry.generic.postalAddress.addressType == AddressType.LegalAndSiteMainAddress) { //Association of Site Main Address to Legal Address
There is some duplicated code here. Why not somthing like:

```
val siteMainAddress = 
            if(genericBusinessPartner.postalAddress.addressType == AddressType.LegalAndSiteMainAddress) 
                legalEntity.legalAddress 
            else  
                createLogisticAddress(mainAddress, taskEntryBpnMapping)
        
  createSite.mainAddress = siteMainAddress
  siteMainAddress.site = createSite
  createSite
```

2023-12-07 03:57 UTC, nicoprow requested changes
See the comment

2023-12-07 09:32 UTC, merged

2024-02-19 09:02 UTC, dilipdhankecha2530 commented
@nicoprow @alexsilva-CGI 
We also need to think for the new endpoints which will do the same. In the current development there is no endpoint which we can use to create LegalEntity address as a SiteAddress.