Fix trivy findings on spring boot image
eclipse-tractusx/bpdm pull request #707
Opened 2024-01-07 23:11 UTC by fabiodmota

## Description
Fix Spring vulnerability's reported by Trivy Scan

https://github.com/eclipse-tractusx/bpdm/issues/706

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-01-09 04:50 UTC, nicoprow requested changes
Looks good to me, just needs some adjustment to the changelog

2024-01-09 04:50 UTC, nicoprow commented on CHANGELOG.md
> +## [4.1.1] - [unreleased]
It's great that you thought about the changelog. However we are already on version 5.0.0 unreleased.

2024-01-10 15:14 UTC, fabiodmota commented
@nicoprow corrected changelog version on CHANGELOG.md

2024-01-10 15:15 UTC, fabiodmota commented
> Looks good to me, just needs some adjustment to the changelog

@nicoprow  corrected changelog version on CHANGELOG.md

2024-01-11 04:43 UTC, nicoprow approved these changes
Please squash the commits or rename the second commit.

2024-01-11 04:43 UTC, merged