Feat/pool client api module
eclipse-tractusx/bpdm pull request #75
Opened 2023-03-14 11:19 UTC by fabiodmota

Add maven module pool client and moving it to the pool module

2023-03-14 13:08 UTC, nicoprow requested changes
The package structure is a bit unconventional for a library. My suggestion would be to rename the packages to:
config -> client
dto -> model (as in model of the api)
service -> (extract api interfaces to root, so the package name is bpdm.pool.api)

In the pool test directory is the util.EndpointValues class which now contains some unused constants since you have replaced the webclient with the poolclient. Please remove the unused constants there.

2023-03-14 13:08 UTC, nicoprow commented on bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/AddressControllerIT.kt
> +        val response = poolClient.addresses().updateAddresses(toUpdate);
Unnecessary semicolon

2023-03-14 13:08 UTC, nicoprow commented on bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/LegalEntityControllerIT.kt
> +       val response = poolClient.legalEntities().getLegalEntity(identifierToFind.value,identifierToFind.type.technicalKey);
Unnecessary semicolon

2023-03-14 13:08 UTC, nicoprow commented on bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/LegalEntityControllerIT.kt
> +        val response = poolClient.legalEntities().getLegalEntity(identifierToFind.value,identifierToFind.type.technicalKey);
Unnecessary semicolon

2023-03-14 13:08 UTC, nicoprow commented on bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/SiteControllerIT.kt
> +        val response = poolClient.sites().updateSite(toUpdate);
Unnecessary semicolon

2023-03-14 13:08 UTC, nicoprow commented on bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/SiteControllerIT.kt
> +    private fun requestSitesOfLegalEntity(bpn: String) = poolClient.legalEntities().getSites(bpn,PaginationRequest());
Unnecessary semicolon

2023-03-14 16:52 UTC, fabiodmota commented
All changed according to the requests

2023-03-15 13:31 UTC, nicoprow approved these changes

2023-03-16 08:09 UTC, merged