feat(bpdm): post endpoint to upload business partner data using csv file
eclipse-tractusx/bpdm pull request #964
Opened 2024-06-12 11:40 UTC by SujitMBRDI

## Description

This pull request contains changes for new POST api endpoint on BPDM Gate service, which will accept the CSV file as input for upsetting business partner input data. This endpoint enable way for user to create/update business partner using file.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-06-12 12:01 UTC, SujitMBRDI commented
@nicoprow,
In general, I tried covering almost all necessary changes. 
Just except,  REST API conformity with permissions about new resource and will also adjust default realm files for both helm chart and test.

2024-06-18 04:14 UTC, SujitMBRDI commented
> @nicoprow, In general, I tried covering almost all necessary changes. Just except, REST API conformity with permissions about new resource and will also adjust default realm files for both helm chart and test.

@nicoprow, I have adapted changes this changes. Kindly review the changes made.

2024-06-18 06:01 UTC, nicoprow requested changes
Since we add a new feature here we should update the POM version to 6.1.0-SNAPSHOT. Likewise, this version upgrade should be written in the Charts as well as described in a comment below

2024-06-20 05:43 UTC, SujitMBRDI commented
> Since we add a new feature here we should update the POM version to 6.1.0-SNAPSHOT. Likewise, this version upgrade should be written in the Charts as well as described in a comment below

I rebased current branch with main, so now just updated chart version to 5.0.3-SNAPSHOT as you already created SNAPSHOT versions.

2024-06-20 05:43 UTC, SujitMBRDI commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/model/PartnerUploadFileRow.kt
> +    @CsvBindByName(column = "externalId")
Done

2024-06-20 05:44 UTC, SujitMBRDI commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/PartnerFileUtil.kt
> +                    validFrom = row.statesValidFrom?.let { LocalDateTime.parse(it, formatter) },
Adapted with new function

2024-06-20 05:45 UTC, SujitMBRDI commented on bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/PartnerUploadControllerIT.kt
> +class PartnerUploadControllerIT @Autowired constructor(
Created new test which covers check for the expectation on created business partner input data.

2024-06-20 05:45 UTC, SujitMBRDI commented on charts/bpdm/Chart.yaml
>  appVersion: "6.0.1"
Done

2024-06-20 05:52 UTC, SujitMBRDI commented on bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/PartnerUploadErrorResponse.kt
> +    val error: List<String>,
As mentioned on sig release issue [700](https://github.com/eclipse-tractusx/sig-release/issues/700).
More information may come from Juila so, for now i haven't refactored this much.But yes in future we can refactor this. Keeping this for future scope, hope you agree with this.

2024-06-20 05:53 UTC, SujitMBRDI commented on bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GatePartnerUploadApi.kt
> +    @PostMapping("/input/partner-upload-process/upload-partner-csv", consumes = ["multipart/form-data"])
Done

2024-06-20 06:37 UTC, nicoprow commented
> > Since we add a new feature here we should update the POM version to 6.1.0-SNAPSHOT. Likewise, this version upgrade should be written in the Charts as well as described in a comment below
> 
> I rebased current branch with main, so now just updated chart version to 5.0.3-SNAPSHOT as you already created SNAPSHOT versions.

I the current app version is 6.0.1-SNAPSHOT. Since this pull request adds a new feature to the app, we need to increase the SNAPSHOT version to 6.1.0-SNAPSHOT. Likewise, we need to increase the chart's SNAPSHOT version to 5.1.0-SNAPSHOT as well as update its appVersion to the 6.1.0-SNAPSHOT.

2024-06-20 07:46 UTC, SujitMBRDI commented
> > > Since we add a new feature here we should update the POM version to 6.1.0-SNAPSHOT. Likewise, this version upgrade should be written in the Charts as well as described in a comment below
> > 
> > 
> > I rebased current branch with main, so now just updated chart version to 5.0.3-SNAPSHOT as you already created SNAPSHOT versions.
> 
> @SujitMBRDI I the current app version is 6.0.1-SNAPSHOT. Since this pull request adds a new feature to the app, we need to increase the SNAPSHOT version to 6.1.0-SNAPSHOT. Likewise, we need to increase the chart's SNAPSHOT version to 5.1.0-SNAPSHOT as well as update its appVersion to the 6.1.0-SNAPSHOT.

@nicoprow, Done. I have adapted changes.

2024-06-20 08:44 UTC, nicoprow approved these changes
Looks good to me

2024-06-20 08:44 UTC, merged